<?php

namespace App\Api;

class Api
{
    /**
     * Função que busca o usuario na api do rm
     * 1 Parametro key via get
     * @var string key
     */
    public static function UserAPI($key)
    {
        //INTRA
        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL => 'https://intra.ubm.br:8080/rm/api/TOTVSEducacional/GetSession?key=' . $key,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'GET',
            CURLOPT_HTTPHEADER => array(
                'Cookie: CorporePrincipal=eHpvUnB3cG1kUURFMTdPYVFIcHRrRnF6NHRPM09ubUhpMVVhcGtGRHpYUHdQQlpJZmFhQlZ3RnRCWmpVUnZKNEZLQVcyYURFSWVLWERrOGdlNzBBR0VIUThzY2lZZndVZlFtdnhmbTZnN1pZb0tHZ3ZSdmQxYjRDRm5rS21Ka0F6TytGUXVia0wyZkEzZHI5cUdvSVYrZ3BPL1pzZWREM1NBTEdhWjFPcFYrRkZhTElYejVtV1pyTEx6aUYvbHhaL01HZzVSOXFGR1FscHVVSTZDRkRRdWNYWHpKQ3luUE5IVDhYVmYzMXM5VEdhMDFVTFM0YWZld2RNS1dTckpDY2N6Z1VpRCtlTXpIVjFKYkEwYUxkT3VaU0JXaXduT0ZVamJWQk1MQzBMc0ZQWDUxbGNGZ0FoNTNnSk1HU2Z0K0ZEa0ttV1dwMDgzYjRDcEJWRjUrMXFZRGRMeVhVRXFKcVpNL3FyNUZaeE1IaktCWmlDT01wRnozdnIyUE5YR1c0enRaQWJXMFNldlJHdWJOTGJuMFZFRG9kTENxeHhGSnJ5Z2xUaGJDbGZjeWhLNFk2Z0lDZ1pRS0ZsYmVjUWFlU0JBNXZzWFRGYmlwMkgyeXdLczZYcGsvbkhCZHFoRmxSNHBDeDIraTdhL2NoQU5EZGhtRE9zMGdOTE83TGYxQnBuTDJtNmx4K0Uyd3BrZ215UDhlaC9qZEdJa3kxd2wrTjJNb0dDc1lxaHpZZkxyVldLOGxiZk5hNzJoaVdlWXVrenl4WjhURWhuK0xLUFJ6dlpFVG5MTVRIVGduZm94ZjEyQWRUWGtWUDZKWEFCeGxEL1FReFpXeVpPVVhBcDY3OHdSTzN3ZE1nUU1hN1pyQ25Fa0VnS0p1c2pjRVJJTllRWTU5Q1lISzhpTFA0MVEzelRvVGF4MWxuMEtHMTRzVFoxUk5qRlNYaitITHJRb0dKZm45amd2VEVBSXlNdXJMNXNiaU9ZZVVwc2syanVaNFlKQzVaaW03RlRvOUl3ak9iVGtaZGVGQ3hkbU5HUmg0VkxKUUloclJHWjJNRkhBRno1Sk1ET1BiQlFVWGxBWUpYWTdQdjRBYjg1REVFaHBkZkorRThvd0p6ckZGY3doSmMxTTE0R2dHZkNScVd2S1h6dytlSDd2V29WNlRWekJoUGpZSXpCK1pUWCtiY3NpelI4S0Y4dWRLZHBkeXZsVUJqa0Q3d0I3bll6UzZ2WkJITXAwY3Z5Q250ckZxaC9lN2xHQUFLT09Jb3VOQ1VTa1o4a3NKdklTdjlwcnBNN0xvNDJoZVBTV2srbFpzTFdOeGN6Z01KdnJRWUV4aGNwZUZTeVBPRm1DT1JzUlVaZUpLajNJeHFHcEVidmJDUXRBVk81L1Y4ZTlUWWFOZzJzeUNCMDAyQ0E1T1kyUlc0MGlGUjRPeXA5cTBndElhRXF5aWlqUXFCdmhSOFF1RmM5K3lrOG9KZVNEamg5a01QK24zbDZFV3JUQWxsMUloZUZVdHBkVWZSR090UmdkVVRwYy8rTTRIZE9HMWdPSm1KanlNb0FZQVR5STFlK0tUc1dHaDVxbHpZRkkySE1sU3YvZitMbGtrS3l5WmU4NlFTSENUY0ZpdEp5Yzc4WWtnZnZFL2VmNThjWThldFhha3hkenhWd1RBUmVzRW9Udmk4NWRlUUU2U2xNOUlUYXhIeSt6RUR4TEZ5VDBWaHo4SUVzQ3hBNzVlK2IzYXN3NTFiQjRoL1VMd0QxRnFKVjhJcmhSL3F0NnBKL1FxNWsvblo3M20va1F1V0xmTThlSm5Mcko3RlloT2ZIREhQM0hrSXVjTkNoNUpoNkEraXBMVkZEaEU4c2NKQ21HbzBLMm90R0dOQXVVRnFlVzFCczZGQkdsS3RhRHBSbm1rZE9YTlFNNVNKS1ZlT3l1dW5wVUJtMThwV2JvNE9RVDBhaEFGcjZZVUsyYUgzMXBlQmljMUQ1RUtwLzAwd3hjYnJkb002T1BvV2tWUkgzalg1c0Yrem9kektQVzlQb3VBZ1RhWVhiOWFsVjl1d01nWFMxL3dlMVFJZEJNMklsOWYvTEt3OTUrallXQzIrdHBSVFhBb1NkNzFyQ2F4VlZBUmJlSExqVlJGbldTcTZFL0pkTkE5QXVrRkxJWGZ6RUtaZHpJNFBvQ1orYUNmbnY4cTZGMXZ2djdtNTJDbExCTHo3a3V6M0xJSU9VR2d2YnpwUUZsclhWNGdTK2pDaEptTzZvZUpGb0gxTEpNSXc1N3BPU3FrMHp6YmVMOTVXVVJ2RUl1OXl3a1doV2dkSThQeWJZK2lUUXBkcFJRbFB4YmRQRW1hT205Skp2WmNOMHQ1Zkdxb1doaEtkajlza3JnMlVuNXNpdzEzWU1EOGtZVTIyb0I5UGNKSmNobkZCUUlLbFBhYkVHa2p2R2JjZXhHdThXcFk5Z0UwVEwrSmM3MlowZ0hvUzJ0TDlTUlJqdWg0T01oRnNWN1RtOVJTZ0ZRajFtMldwTnFqb2ZhZUxHZ3prUzMrbkZyc1g0b1pUclA2ZjB1LzE3UER6NUhNZnRMVmpURnl2a2Y3WFBTRC9DS3kvcDdMZXVpQk5YaEMzd2RhcUhxSTZGQjhZZC8yMHhDeDlqZ0JMMG9MbVdFcTY3ZTNtaVVoL0Q3d3VWWldWZ1dmemg2MTRDV1Y2R2FJZmZsRUNSaTVjbmpsSFRFMkZ2UzVHSVNjT3NyRENNSE9xQ2xOcWFmdWJRQ21nVlhud1NwaHkrbjVFcHdvZVB0NWFNV1FHWkFrcFRoNmNPa0VNbUdOaEJkYm93cGJTU1E5aTN3eDhvWENCbXRoOEdtNzE0TjkybWlFdjNpZjRNWFB5eExMaStTb0lHVHdlQ0E0M1pkb2xiUVNoWDdPZw; DefaultAlias=CorporeRM'
            ),
        ));

        global $response;
        $response = json_decode(curl_exec($curl));

        curl_close($curl);



        //PORTAL
        // $curl = curl_init();

        // curl_setopt_array($curl, array(
        //     CURLOPT_URL => 'http://portal.ubm.br/FrameHTML/rm/api/TOTVSEducacional/GetSession?key=' . $key,
        //     CURLOPT_RETURNTRANSFER => true,
        //     CURLOPT_ENCODING => '',
        //     CURLOPT_MAXREDIRS => 10,
        //     CURLOPT_TIMEOUT => 0,
        //     CURLOPT_FOLLOWLOCATION => true,
        //     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        //     CURLOPT_CUSTOMREQUEST => 'GET',
        //     CURLOPT_HTTPHEADER => array(
        //         'Cookie: CorporePrincipal=cm4wS04wOENoanRFU2hmbUNOMGkzbVZ2ZUpLRnZYTEZ3Q1hNYjBrM094cHM3Vi9samNKMEs3RTVEd0dqNzZXRzlUS1ROLzFNZ0pyRVVjQnU3ZU02U1dKQ3BRR0EzZjFDRHNPRFE0QU5wVlI0QVBoWFZsYmxzaFphUFRnRXpOV294NDRuWExCNEZNakF6UzNJUnZZTUVsczRlUVJkaFBqM3VzZ0dtcEMrVHp3a3dIQlJCTTFBQ2kra3dadnd3a0xIRTV5b1RKVmxZYUJLelY0TjFsTnVhMHNFZGI4cjliayszVmNlY2dPbUh2Mmcybm1UOSsvZ21Nb1pRS0pkMzl3VWRjci9vQWxRSUt3UXZVOVVYK3FmcFl4Tlc1M0tCeVBVbm94ajBUZXhuV28rWDEzNHJ5Z2FtcVVFQTRtRUF2UjZmWGc0NzNGQlk2TjZ3MmRsOVVKM3Y4Zm9GT1JmQVJyclRjQTEvRzlWZUF6NW9NS3FJUnhyODZpdUFRMHBmQmJ2VitUYW1qMi9zbUd5ZjhLWmdEd2hyQWRrQitaQmJOeG50TXZ0Um14VXNOczlaNDZzMWJJOXJhV1FIL21Sc1E5RTZ1Um9sS0JYemhCaGVNRk5pbWRVem9XNHRiUlltU3IyZ0lsOEFlS0N4Sk5wQ1Rac2hKS1JzVDNpc0ZqTFdqQWROMzh5RnA2NFUyV1hDTDkya3J4WHFlb3VlNWRmdjR4UStpYnJYVUpEcXlBdUN0SkZvNWJ2M0hwS1hVc1NxZlFFZ2dzYXU4U1FDM3VNNWRoVDZiOTlWR1lpWmJZSHJZRlFKTTVSVFErS1QyVHRZRFZmZnpFdXJsUXYyR0NkOWorMU8vVThpLzFyT0hodHZlQy9FdGN1eGo3d29zSllJTFJld2E5c21yZWNja0ZqTzZBQnNBRjQzTVZmdkxRSVkwZGtxakg2czhjdE91ZmpOQnIrRGNCcmhoZWpJOW56TGJLNmxxVlFGUDlKQjhZUWhIVjZHcjEzUElHcFBQTExMN3lHdFJpMVYxZnV2TWh2WVpPRFlNWVlwa2VWbzhVMVNvd3hhWTNhaEIycWdoTmN2ejRpd3E1b2JVZGcwZ0c4QXE2NmpBTGVqZENDTUlUZ1diL2h5WlVTeTl6Yi9QRUVXeUZiYWtVR0Y4QkRBeUV6NGR3cmdxbFIvcjJ4Z2dzSGF5QlZHN01sK3A5ZE0zMTJDQlhsZlF2S2Y2REFYbzdJMlFnMWJ3cGhjMFVueWxJbFZaemFaQkgwWnkzWXpVSmMvbnh0S05rcTVJLzBacytHSG9pTmNCNXN2K3UvY0o2bkxXbFRkbXFvNzdSNmV5cVZpWFVMdGNBc0tQekxpeE55SHhJbHoxb2NXSHlKVTJhRHZSWDd2MTFHdDZkNWFQTXBUdnJNSnp3WG1GRHlucFdia245TXlEdzVOb3QyaTNsL0Uwd083dE1pc3FWdGhNQnRqNFJrTy9KUkl5ZUk1NXJHYzFhU3U3M09XL1hIbHgzUDJpbkUvOTBSREZnWnc5UHFMK3d6a1c1b09EQ1dLRGxIVDdnM3RXV0pWUmtYcHMrVVFLeGFJcHNGVENtb3AyVDdveldWd3JjNmYxc2JYRVlrNTdmdlNZRWpYVHBqcXBwakRTMnUydTgwdFNLOGFXWFZ1YUdMWlhrWXArd0dibEhhZ0RWYkVmdEQ0T0IrblVHOCt3UERrc2VuVVd2NjNZaFlzNWVDcnpyeVBaMnFGVGt4NUdIVVdTVmlidUpnTnZkRmdiWDIvK1NMb2krYUE1dmhnejRib0FhR1g5VTJmbEFYTHhGN0dObGhRTTNvQXdKTWhuTTRncWVPdnVKS0Fid0ZtcGJrcitoelZUeW9JM21iOXYybDhaeFlvYUZ5WGNISUFrbzZFZ2o5a3dqRWdFUm9HTU05blJYa2h1cTZFdks2U3dLTXpGRDJTMC9lUzFBNXVEaUVvQnlSdmcrOERUUlBidFVUaHJoMi9TcCsvbnJXWnYrL1A1MUZGM25GSTJLcUNlQ0tXdkdEMkdvdVE0RVMxT1pjd0U0TlZOSWFBWFdkK0Q4azZKU3Q5V21ST3BUQUcrQ1o3d3AvOVNrQjdsS0VvRFpQZE55d1RIdy81ZHJLeGJCcGlsTkVFQVpLbnQwWkxEZFRHOGpySE9mUkFwRUhoU1NPUVJ2S1Y5Yy9CVDd1MWNaOHBldWFuTWhNWmRJY1dWbXVyc3I5UVZ5c0t5SCtNTG4xTmVJcDhOdnl5VnJRZEYxbEVSTmtINnhOK21oZEVndWJmTUYwcGl5bmZkNUlWQmRFdTJhR1crQmUvWWNmOFZXR1hzRUZySWVqYUNMelZvdGNJYmRWSmtzekpmZnErTTJMeW9LM1Q2MHB2WlY4TFNVbC9zTTdmaWgzUGMvK1JyeHplbGIyRUdLbFl2T3RFU0FHTjZURGRiNlAyTThMVVVFZWZMQVpVWCtEb0wwR3RlRlNOWW9OM2pKcnJZY1NkY0dBSmZCUEFqaFJqbURFYUNvNk9hb2NZNEFSeDZuTy9iTTNhZGhKTnk3dFIvbFMxRlkvdHFpdTdkNkRjZGZLQmlUM201V1M1VldNRjhMNHR1ZHk0bzUxSCs2amhiZCtScWFYUFlaRGlKREptU2tyNGw0MGVhcjdVZzNUNEFZKytVUENaS29WWlVTaUIraHAyZWtKUXdLb2V0NHEyU0djbDd6b3dmZkQvaDVlVEZDRXYvVEk3dlVzV2IxVG9LTlhvZ0tpYkxZUlpzOHdBYm1rekQrdE9DNzdoL3VlQmVYcXlDZnlLNHQ4RFowTnRiSUpwbm9wZ3EwOGRWWG8yUkFyU3lhZlpocmlnZz09; DefaultAlias=CorporeRM_TESTE_SSTRH'
        //     ),
        // ));

        // global $response;
        // $response = json_decode(curl_exec($curl));

        // curl_close($curl);

        // echo "<pre>";
        // print_r($response);
        // echo "<pre>";
        // die();
    }
}
